[[language]]
name = "nix"
language-servers = ["nixd"]
auto-format = true
formatter = { command = "nixfmt" }

[language-server.nixd]
command = "nixd"

[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "bash"
language-servers = ["bash-language-server"]

[language-server.fish-lsp]
command = "fish-lsp"
args = ["start"]

[[language]]
name = "fish"
language-servers = ["fish-lsp"]

[language-server.markdown-oxide]
command = "markdown-oxide"

[[language]]
name = "markdown"
language-servers = ["markdown-oxide"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[language-server.ruff-lsp]
command = "ruff"
args = ["server", "--preview"]

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ty", "ruff-lsp"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true
